### ISSUE TITLE
Result little bit Weird

### ISSUE THREAD

**Issue by herleeyandi** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#15]
Hi I am using pytorch 0.4. I use your notebook to run simulation. Thank you for your works, it really the best tutorial. After I follow your setting and just run it I have a weird result like the different people has lower dissimilarity. I try to train again with bigger epoch and check if your code input wrong pairs of image. However after I checked all is well. Your data loader is also right but I have bad result for dissimilarity where the same person has higher dissimilarity but in some cases the different person has lower dissimilarity. Should I change the siamse network architecture?, thank you.

![image](https://user-images.githubusercontent.com/2309538/41898527-d5af3990-795c-11e8-966c-13396edd45e6.png)

![image](https://user-images.githubusercontent.com/2309538/41898589-fe2507a6-795c-11e8-86fc-f3403b524736.png)

**Comment by harveyslash** [comment]
There are several similar issues that people have brought up. 
It is possible that the dataset was too small for such a large network, and I got good results by chance the first few times that i tried. 

I am working on using the face scrub dataset instead of at&t. It has a lot more images. 

The network itself should work though. You can try it with some other dataset.

**Comment by herleeyandi** [comment]
@harveyslash Thank you so much, good job and article, can't wait to read your next article to resolve this issue.

**Comment by luosyx** [comment]
#27 
 Maybe this can solve your problem~

**Comment by harveyslash** [comment]
I am trying to restart work on this project, including better models and a larger dataset. please let me know if you are interested.
